// Exact item pool for Pokémon Champions, curated from the in-game item list
// (Serebii's Champions ItemDex, cross-checked against the game's own item
// listing). This is deliberately NOT the full Gen 9 competitive item pool —
// Champions launched with a smaller, more classic set. Notably absent versus
// modern VGC: Choice Band, Choice Specs, Assault Vest, Heavy-Duty Boots,
// Rocky Helmet, Eviolite, Booster Energy, Covert Cloak, Loaded Dice, Safety
// Goggles, Weakness Policy, Clear Amulet, Air Balloon. If/when Champions adds
// these in a future update, add them to HOLD_ITEMS below.

export const HOLD_ITEMS = [
  "Big Root",
  "Black Belt",
  "Black Glasses",
  "Bright Powder",
  "Charcoal",
  "Choice Scarf",
  "Damp Rock",
  "Dragon Fang",
  "Expert Belt",
  "Fairy Feather",
  "Focus Band",
  "Focus Sash",
  "Hard Stone",
  "Heat Rock",
  "Icy Rock",
  "Iron Ball",
  "King's Rock",
  "Leftovers",
  "Life Orb",
  "Light Ball",
  "Light Clay",
  "Magnet",
  "Mental Herb",
  "Metal Coat",
  "Metronome",
  "Miracle Seed",
  "Muscle Band",
  "Mystic Water",
  "Never-Melt Ice",
  "Poison Barb",
  "Quick Claw",
  "Scope Lens",
  "Sharp Beak",
  "Shed Shell",
  "Shell Bell",
  "Silk Scarf",
  "Silver Powder",
  "Smooth Rock",
  "Soft Sand",
  "Spell Tag",
  "Twisted Spoon",
  "White Herb",
  "Wide Lens",
  "Wise Glasses",
  "Zoom Lens",
  // Regulation M-C additions (Sept 2026)
  "Air Balloon",
  "Binding Band",
  "Eject Button",
  "Electric Seed",
  "Grassy Seed",
  "Leek",
  "Misty Seed",
  "Normal Gem",
  "Psychic Seed",
  "Red Card",
  "Rocky Helmet",
  "Terrain Extender",
];

export const BERRIES = [
  "Aspear Berry",
  "Babiri Berry",
  "Charti Berry",
  "Cheri Berry",
  "Chesto Berry",
  "Chilan Berry",
  "Chople Berry",
  "Coba Berry",
  "Colbur Berry",
  "Haban Berry",
  "Kasib Berry",
  "Kebia Berry",
  "Leppa Berry",
  "Lum Berry",
  "Occa Berry",
  "Oran Berry",
  "Passho Berry",
  "Payapa Berry",
  "Pecha Berry",
  "Persim Berry",
  "Rawst Berry",
  "Rindo Berry",
  "Roseli Berry",
  "Shuca Berry",
  "Sitrus Berry",
  "Tanga Berry",
  "Wacan Berry",
  "Yache Berry",
];

// Every Mega Stone confirmed in the Champions item list, mapped to the
// species it activates. Not every one of these has playable Mega stats wired
// up yet in MEGA_SPECIES below (see champions/megaSpecies.ts) — holding an
// unsupported stone just acts as a normal (no-effect) held item for now.
export const MEGA_STONES: { item: string; species: string }[] = [
  { item: "Abomasite", species: "Abomasnow" },
  { item: "Absolite", species: "Absol" },
  { item: "Aerodactylite", species: "Aerodactyl" },
  { item: "Aggronite", species: "Aggron" },
  { item: "Alakazite", species: "Alakazam" },
  { item: "Altarianite", species: "Altaria" },
  { item: "Ampharosite", species: "Ampharos" },
  { item: "Audinite", species: "Audino" },
  { item: "Banettite", species: "Banette" },
  { item: "Barbaracite", species: "Barbaracle" },
  { item: "Beedrillite", species: "Beedrill" },
  { item: "Blastoisinite", species: "Blastoise" },
  { item: "Blazikenite", species: "Blaziken" },
  { item: "Cameruptite", species: "Camerupt" },
  { item: "Chandelurite", species: "Chandelure" },
  { item: "Charizardite X", species: "Charizard" },
  { item: "Charizardite Y", species: "Charizard" },
  { item: "Chesnaughtite", species: "Chesnaught" },
  { item: "Chimechite", species: "Chimecho" },
  { item: "Clefablite", species: "Clefable" },
  { item: "Crabominite", species: "Crabominable" },
  { item: "Delphoxite", species: "Delphox" },
  { item: "Dragalgite", species: "Dragalge" },
  { item: "Dragoninite", species: "Dragonite" },
  { item: "Drampanite", species: "Drampa" },
  { item: "Eelektrossite", species: "Eelektross" },
  { item: "Emboarite", species: "Emboar" },
  { item: "Excadrite", species: "Excadrill" },
  { item: "Falinksite", species: "Falinks" },
  { item: "Feraligite", species: "Feraligatr" },
  { item: "Floettite", species: "Floette" },
  { item: "Froslassite", species: "Froslass" },
  { item: "Galladite", species: "Gallade" },
  { item: "Garchompite", species: "Garchomp" },
  { item: "Gardevoirite", species: "Gardevoir" },
  { item: "Gengarite", species: "Gengar" },
  { item: "Glalitite", species: "Glalie" },
  { item: "Glimmoranite", species: "Glimmora" },
  { item: "Golurkite", species: "Golurk" },
  { item: "Greninjite", species: "Greninja" },
  { item: "Gyaradosite", species: "Gyarados" },
  { item: "Hawluchanite", species: "Hawlucha" },
  { item: "Heracronite", species: "Heracross" },
  { item: "Houndoominite", species: "Houndoom" },
  { item: "Kangaskhanite", species: "Kangaskhan" },
  { item: "Lopunnite", species: "Lopunny" },
  { item: "Lucarionite", species: "Lucario" },
  { item: "Malamarite", species: "Malamar" },
  { item: "Manectite", species: "Manectric" },
  { item: "Mawilite", species: "Mawile" },
  { item: "Medichamite", species: "Medicham" },
  { item: "Meganiumite", species: "Meganium" },
  { item: "Meowsticite", species: "Meowstic" },
  { item: "Metagrossite", species: "Metagross" },
  { item: "Pidgeotite", species: "Pidgeot" },
  { item: "Pinsirite", species: "Pinsir" },
  { item: "Pyroarite", species: "Pyroar" },
  { item: "Raichunite X", species: "Raichu" },
  { item: "Raichunite Y", species: "Raichu" },
  { item: "Sablenite", species: "Sableye" },
  { item: "Sceptilite", species: "Sceptile" },
  { item: "Scizorite", species: "Scizor" },
  { item: "Scolipite", species: "Scolipede" },
  { item: "Scovillainite", species: "Scovillain" },
  { item: "Scraftinite", species: "Scrafty" },
  { item: "Sharpedonite", species: "Sharpedo" },
  { item: "Skarmorite", species: "Skarmory" },
  { item: "Slowbronite", species: "Slowbro" },
  { item: "Staraptite", species: "Staraptor" },
  { item: "Starminite", species: "Starmie" },
  { item: "Steelixite", species: "Steelix" },
  { item: "Swampertite", species: "Swampert" },
  { item: "Tyranitarite", species: "Tyranitar" },
  { item: "Venusaurite", species: "Venusaur" },
  { item: "Victreebelite", species: "Victreebel" },
];

// Reg M-C additions — names confirmed against Bulbapedia's Mega Stone
// category listing (not guessed).
export const NEW_MEGA_STONES: { item: string; species: string }[] = [
  { item: "Salamencite", species: "Salamence" },
  { item: "Golisopite", species: "Golisopod" },
  { item: "Baxcalibrite", species: "Baxcalibur" },
  // "Z" stones: Absol, Garchomp and Lucario each have TWO distinct stones —
  // the classic one (unlocks the ORAS-era Mega) and this one (unlocks the
  // Champions/Mega Dimension "Z" forme). Confirmed via Bulbapedia.
  { item: "Absolite Z", species: "Absol" },
  { item: "Garchompite Z", species: "Garchomp" },
  { item: "Lucarionite Z", species: "Lucario" },
];

export const CHAMPIONS_ITEM_NAMES = [
  ...HOLD_ITEMS,
  ...MEGA_STONES.map((m) => m.item),
  ...NEW_MEGA_STONES.map((m) => m.item),
  ...BERRIES,
].sort((a, b) => a.localeCompare(b));