import type { StatKey } from "../gen";

export interface MetaSet {
  item: string;
  ability: string;
  nature: string;
  /** Stat Points (0-32 each), only the invested stats need to be listed. */
  sp: Partial<Record<StatKey, number>>;
  moves: string[];
  source: string;
  /** False when the exact Stat Point spread wasn't confirmed at the source
   * and a sensible default was used instead — item/ability/nature/moves are
   * still real, sourced data either way. */
  spConfirmed: boolean;
}

// Curated from real Regulation M-A/M-B/M-C usage data — mainly Pikalytics
// (aggregated usage stats across thousands of ranked battles, the closest
// Champions equivalent to Smogon's own usage stats), cross-checked against
// MetaVGC tournament team pages and Game8 for exact Stat Point spreads
// where Pikalytics' own top-usage spread wasn't fetched. Only covers
// Pokémon that actually see competitive play; the vast majority of the
// Champions Pokédex simply isn't used at this level, so there's nothing
// "meta" to source for them (they keep the generic real-ability + first-4
// -moves autofill instead). This list grows over time — see each entry's
// `source` comment to add more or double check one.
export const META_SETS: Record<string, MetaSet> = {
  // --- Pikalytics usage stats, Champions VGC 2026 Reg M-A (pikalytics.com/pokedex/gen9championsvgc2026regma) ---
  // Top-4 moves/item/ability by usage %, unless noted otherwise.
  Kingambit: {
    item: "Chople Berry",
    ability: "Defiant",
    nature: "Adamant",
    sp: { hp: 32, atk: 32, def: 2 },
    moves: ["Sucker Punch", "Kowtow Cleave", "Protect", "Low Kick"],
    source: "Pikalytics usage stats — top SP spread (Adamant 32/32/0/0/2/0, 6.5% of sets) confirmed",
    spConfirmed: true,
  },
  Garchomp: {
    item: "Choice Scarf",
    ability: "Rough Skin",
    nature: "Adamant",
    sp: { hp: 32, atk: 20, def: 1, spd: 1, spe: 12 },
    moves: ["Earthquake", "Dragon Claw", "Rock Slide", "Protect"],
    source: "Pikalytics usage stats; SP spread from Game8 Movesets and Best Builds",
    spConfirmed: true,
  },
  "Charizard-Mega-Y": {
    item: "Charizardite Y",
    ability: "Drought",
    nature: "Modest",
    sp: { hp: 24, def: 14, spa: 11, spe: 17 },
    moves: ["Heat Wave", "Protect", "Solar Beam", "Weather Ball"],
    source: "Pikalytics usage stats — top SP spread (Modest 24/0/14/11/0/17, 4.8% of sets) confirmed",
    spConfirmed: true,
  },
  Sneasler: {
    item: "White Herb",
    ability: "Unburden",
    nature: "Jolly",
    sp: { hp: 2, atk: 32, spe: 32 },
    moves: ["Close Combat", "Dire Claw", "Fake Out", "Protect"],
    source: "Pikalytics usage stats — top SP spread (Jolly 2/32/0/0/0/32, 13.4% of sets) confirmed",
    spConfirmed: true,
  },
  Incineroar: {
    item: "Sitrus Berry",
    ability: "Intimidate",
    nature: "Impish",
    sp: { hp: 20, def: 24, spd: 20 },
    moves: ["Fake Out", "Parting Shot", "Flare Blitz", "Throat Chop"],
    source: "Pikalytics usage stats; SP is a sensible bulky-support default",
    spConfirmed: false,
  },
  "Floette-Mega": {
    item: "Floettite",
    ability: "Fairy Aura",
    nature: "Timid",
    sp: { hp: 2, spa: 32, spe: 32 },
    moves: ["Protect", "Dazzling Gleam", "Moonblast", "Light of Ruin"],
    source: "Pikalytics usage stats; SP is a sensible special-sweeper default",
    spConfirmed: false,
  },
  Sinistcha: {
    item: "Kasib Berry",
    ability: "Hospitality",
    nature: "Calm",
    sp: { hp: 32, def: 12, spd: 22 },
    moves: ["Matcha Gotcha", "Rage Powder", "Trick Room", "Life Dew"],
    source: "Pikalytics usage stats; SP is a sensible bulky-support default",
    spConfirmed: false,
  },
  Sylveon: {
    item: "Fairy Feather",
    ability: "Pixilate",
    nature: "Modest",
    sp: { hp: 4, spa: 32, spe: 30 },
    moves: ["Hyper Voice", "Quick Attack", "Protect", "Hyper Beam"],
    source: "Pikalytics usage stats; SP is a sensible special-attacker default",
    spConfirmed: false,
  },
  Whimsicott: {
    item: "Focus Sash",
    ability: "Prankster",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Tailwind", "Moonblast", "Encore", "Protect"],
    source: "Pikalytics usage stats; SP is a sensible speed-support default",
    spConfirmed: false,
  },
  Archaludon: {
    item: "Leftovers",
    ability: "Stamina",
    nature: "Sassy",
    sp: { hp: 32, def: 1, spa: 2, spd: 20, spe: 11 },
    moves: ["Flash Cannon", "Protect", "Electro Shot", "Dragon Pulse"],
    source: "Pikalytics usage stats (item); SP spread from a 1st-place MetaVGC tournament team",
    spConfirmed: true,
  },
  Farigiraf: {
    item: "Sitrus Berry",
    ability: "Armor Tail",
    nature: "Sassy",
    sp: { hp: 32, def: 12, spd: 22 },
    moves: ["Trick Room", "Psychic", "Helping Hand", "Protect"],
    source: "Pikalytics usage stats; SP is a sensible slow-support default (fits Trick Room)",
    spConfirmed: false,
  },
  "Aerodactyl-Mega": {
    item: "Aerodactylite",
    ability: "Tough Claws",
    nature: "Jolly",
    sp: { hp: 2, atk: 32, spe: 32 },
    moves: ["Rock Slide", "Dual Wingbeat", "Tailwind", "Protect"],
    source: "Pikalytics usage stats — top SP spread (Jolly 2/32/0/0/0/32, 14.0% of sets) confirmed",
    spConfirmed: true,
  },
  Pelipper: {
    item: "Sitrus Berry",
    ability: "Drizzle",
    nature: "Modest",
    sp: { hp: 31, def: 1, spa: 5, spd: 18, spe: 11 },
    moves: ["Hurricane", "Weather Ball", "Tailwind", "Wide Guard"],
    source: "Pikalytics usage stats (moves/item); SP spread from a 1st-place MetaVGC tournament team",
    spConfirmed: true,
  },
  Sableye: {
    item: "Roseli Berry",
    ability: "Prankster",
    nature: "Calm",
    sp: { hp: 32, def: 12, spd: 22 },
    moves: ["Light Screen", "Rain Dance", "Encore", "Reflect"],
    source: "Pikalytics usage stats; SP is a sensible bulky-support default",
    spConfirmed: false,
  },
  "Dragonite-Mega": {
    item: "Dragoninite",
    ability: "Multiscale",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Tailwind", "Dragon Pulse", "Protect", "Hurricane"],
    source: "Pikalytics usage stats; SP is a sensible special-sweeper default",
    spConfirmed: false,
  },
  Maushold: {
    item: "Chople Berry",
    ability: "Friend Guard",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Follow Me", "Protect", "Super Fang", "Feint"],
    source: "Pikalytics usage stats; SP is a sensible support default",
    spConfirmed: false,
  },
  Aegislash: {
    item: "Spell Tag",
    ability: "Stance Change",
    nature: "Quiet",
    sp: { hp: 4, atk: 28, spa: 28, spe: 6 },
    moves: ["Shadow Sneak", "Poltergeist", "King's Shield", "Iron Head"],
    source: "Pikalytics usage stats; SP is a sensible mixed-attacker default",
    spConfirmed: false,
  },
  "Blastoise-Mega": {
    item: "Blastoisinite",
    ability: "Mega Launcher",
    nature: "Modest",
    sp: { hp: 4, spa: 32, spe: 30 },
    moves: ["Water Spout", "Dark Pulse", "Fake Out", "Aura Sphere"],
    source: "Pikalytics usage stats; SP is a sensible special-attacker default",
    spConfirmed: false,
  },
  "Rotom-Wash": {
    item: "Sitrus Berry",
    ability: "Levitate",
    nature: "Bold",
    sp: { hp: 32, def: 22, spe: 12 },
    moves: ["Hydro Pump", "Will-O-Wisp", "Thunderbolt", "Protect"],
    source: "Pikalytics usage stats; SP is a sensible bulky-support default",
    spConfirmed: false,
  },
  Glimmora: {
    item: "Focus Sash",
    ability: "Toxic Debris",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Sludge Bomb", "Power Gem", "Earth Power", "Spiky Shield"],
    source: "Pikalytics usage stats; SP is a sensible special-attacker default",
    spConfirmed: false,
  },
  Aerodactyl: {
    item: "Focus Sash",
    ability: "Unnerve",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Rock Slide", "Tailwind", "Protect", "Dual Wingbeat"],
    source: "Pikalytics usage stats; SP is a sensible fast-attacker default",
    spConfirmed: false,
  },
  Talonflame: {
    item: "Sharp Beak",
    ability: "Gale Wings",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Tailwind", "Protect", "Flare Blitz", "Brave Bird"],
    source: "Pikalytics usage stats; SP is a sensible fast-attacker default",
    spConfirmed: false,
  },
  "Froslass-Mega": {
    item: "Froslassite",
    ability: "Snow Warning",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Blizzard", "Protect", "Shadow Ball", "Aurora Veil"],
    source: "Pikalytics usage stats; SP is a sensible special-sweeper default",
    spConfirmed: false,
  },
  "Scovillain-Mega": {
    item: "Scovillainite",
    ability: "Spicy Spray",
    nature: "Modest",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Rage Powder", "Protect", "Overheat", "Leech Seed"],
    source: "Pikalytics usage stats; SP is a sensible special-attacker default",
    spConfirmed: false,
  },
  Basculegion: {
    item: "Choice Scarf",
    ability: "Adaptability",
    nature: "Jolly",
    sp: { atk: 32, def: 2, spe: 32 },
    moves: ["Last Respects", "Aqua Jet", "Wave Crash", "Protect"],
    source: "Pikalytics usage stats — top SP spread (Jolly 0/32/2/0/0/32, 12.4% of sets) confirmed",
    spConfirmed: true,
  },

  // --- MetaVGC tournament team (Forblaze, 1st — SNT Reg M-C Tour #1) — exact SP confirmed ---
  "Mega Golisopod": {
    item: "Golisopite",
    ability: "Tough Claws",
    nature: "Adamant",
    sp: { hp: 32, atk: 32, def: 2 },
    moves: ["Protect", "Swords Dance", "Iron Head", "Brick Break"],
    source: "Forblaze, 1st — SNT Reg M-C Tour #1 (MetaVGC)",
    spConfirmed: true,
  },
  "Indeedee-F": {
    item: "Colbur Berry",
    ability: "Psychic Surge",
    nature: "Bold",
    sp: { hp: 32, atk: 2, def: 32 },
    moves: ["Follow Me", "Psychic", "Protect", "Trick Room"],
    source: "Forblaze, 1st — SNT Reg M-C Tour #1 (MetaVGC)",
    spConfirmed: true,
  },
  Toxapex: {
    item: "Leftovers",
    ability: "Regenerator",
    nature: "Calm",
    sp: { hp: 32, def: 18, spd: 16 },
    moves: ["Toxic", "Baneful Bunker", "Infestation", "Wide Guard"],
    source: "Forblaze, 1st — SNT Reg M-C Tour #1 (MetaVGC)",
    spConfirmed: true,
  },
  "Swampert-Mega": {
    item: "Swampertite",
    ability: "Swift Swim",
    nature: "Adamant",
    sp: { hp: 25, atk: 26, spe: 15 },
    moves: ["Earthquake", "Wave Crash", "Rock Slide", "Protect"],
    source: "Forblaze, 1st — SNT Reg M-C Tour #1 (MetaVGC)",
    spConfirmed: true,
  },

  // --- Zemar12, 1st place ("Champion"), VGC UmbreNews 08.09.2026 #31 (Pokémon-Zone/MetaVGC) ---
  Chesnaught: {
    item: "Leftovers",
    ability: "Bulletproof",
    nature: "Impish",
    sp: { hp: 20, def: 24, spd: 20 },
    moves: ["Body Press", "Wood Hammer", "Wide Guard", "Spiky Shield"],
    source: "Zemar12, 1st — VGC UmbreNews 08.09.2026 #31 (Pokémon-Zone); SP is a sensible bulky default",
    spConfirmed: false,
  },
  "Gardevoir-Mega": {
    item: "Gardevoirite",
    ability: "Pixilate",
    nature: "Timid",
    sp: { hp: 2, spa: 32, spe: 32 },
    moves: ["Protect", "Hyper Voice", "Trick Room", "Moonblast"],
    source: "MetaVGC most-common-build aggregate for Gardevoir (Timid 2/0/0/32/0/32)",
    spConfirmed: true,
  },

  // --- MetaVGC per-Pokémon "most common build" aggregate — exact SP confirmed ---
  "Mega Chesnaught": {
    item: "Chesnaughtite",
    ability: "Bulletproof",
    nature: "Careful",
    sp: { hp: 32, def: 2, spd: 32 },
    moves: ["Spiky Shield", "Body Press", "Wood Hammer", "Wide Guard"],
    source: "MetaVGC most-common-build aggregate for Chesnaught Mega (Careful 32/0/2/0/32/0)",
    spConfirmed: true,
  },
  "Mega Floette": {
    item: "Floettite",
    ability: "Fairy Aura",
    nature: "Timid",
    sp: { hp: 2, spa: 32, spe: 32 },
    moves: ["Protect", "Moonblast", "Dazzling Gleam", "Calm Mind"],
    source: "Pikalytics usage stats for Mega Floette; SP is a sensible special-sweeper default",
    spConfirmed: false,
  },

  // --- Auto-generated from Pikalytics' live usage feed (Reg M-B S3), decoded via @pkmn/dex --- 
  // item/ability/moves are real, usage-ranked data; Stat Point spreads are role-based
  // defaults (not from this feed) since it doesn't expose EV/SP data — see individual
  // `source` strings. Regenerate via generate_metasets.ts if the feed updates.
  "Charizard": {
    item: "Focus Sash",
    ability: "Blaze",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Protect", "Heat Wave", "Solar Beam", "Weather Ball"],
    source: "Pikalytics live usage feed (Reg M-B S3, 3.66% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Floette-Eternal": {
    item: "Life Orb",
    ability: "Flower Veil",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Protect", "Dazzling Gleam", "Moonblast", "Calm Mind"],
    source: "Pikalytics live usage feed (Reg M-B S3, 2.92% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Staraptor": {
    item: "Choice Scarf",
    ability: "Intimidate",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Close Combat", "Protect", "Brave Bird", "Roost"],
    source: "Pikalytics live usage feed (Reg M-B S3, 2.68% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Raichu": {
    item: "Focus Sash",
    ability: "Lightning Rod",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Fake Out", "Protect", "Zap Cannon", "Focus Blast"],
    source: "Pikalytics live usage feed (Reg M-B S3, 2.32% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Venusaur": {
    item: "Focus Sash",
    ability: "Chlorophyll",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Sludge Bomb", "Protect", "Earth Power", "Giga Drain"],
    source: "Pikalytics live usage feed (Reg M-B S3, 1.82% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Delphox": {
    item: "Choice Scarf",
    ability: "Blaze",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Protect", "Heat Wave", "Nasty Plot", "Psychic"],
    source: "Pikalytics live usage feed (Reg M-B S3, 1.77% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Tyranitar": {
    item: "Chople Berry",
    ability: "Sand Stream",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Rock Slide", "Knock Off", "Protect", "Low Kick"],
    source: "Pikalytics live usage feed (Reg M-B S3, 1.50% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Froslass": {
    item: "Focus Sash",
    ability: "Cursed Body",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Blizzard", "Protect", "Shadow Ball", "Aurora Veil"],
    source: "Pikalytics live usage feed (Reg M-B S3, 1.46% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Swampert": {
    item: "Life Orb",
    ability: "Torrent",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Protect", "Wave Crash", "Earthquake", "Ice Punch"],
    source: "Pikalytics live usage feed (Reg M-B S3, 1.35% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Arcanine-Hisui": {
    item: "Focus Sash",
    ability: "Rock Head",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Flare Blitz", "Extreme Speed", "Protect", "Head Smash"],
    source: "Pikalytics live usage feed (Reg M-B S3, 1.27% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Gholdengo": {
    item: "Life Orb",
    ability: "Good as Gold",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Make It Rain", "Shadow Ball", "Protect", "Nasty Plot"],
    source: "Pikalytics live usage feed (Reg M-B S3, 1.24% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Milotic": {
    item: "Leftovers",
    ability: "Competitive",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Scald", "Protect", "Recover", "Muddy Water"],
    source: "Pikalytics live usage feed (Reg M-B S3, 1.21% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Grimmsnarl": {
    item: "Light Clay",
    ability: "Prankster",
    nature: "Careful",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Light Screen", "Parting Shot", "Reflect", "Spirit Break"],
    source: "Pikalytics live usage feed (Reg M-B S3, 1.20% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Blastoise": {
    item: "Mystic Water",
    ability: "Rain Dish",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Water Spout", "Dark Pulse", "Aura Sphere", "Fake Out"],
    source: "Pikalytics live usage feed (Reg M-B S3, 1.01% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Torkoal": {
    item: "Charcoal",
    ability: "Drought",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Eruption", "Protect", "Weather Ball", "Heat Wave"],
    source: "Pikalytics live usage feed (Reg M-B S3, 1.00% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Scovillain": {
    item: "Kebia Berry",
    ability: "Moody",
    nature: "Calm",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Protect", "Rage Powder", "Overheat", "Leech Seed"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.90% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Excadrill": {
    item: "Focus Sash",
    ability: "Sand Rush",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Iron Head", "Protect", "Rock Slide", "Earthquake"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.89% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Ninetales-Alola": {
    item: "Light Clay",
    ability: "Snow Warning",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Blizzard", "Protect", "Freeze-Dry", "Aurora Veil"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.84% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Gengar": {
    item: "Focus Sash",
    ability: "Cursed Body",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Shadow Ball", "Protect", "Perish Song", "Sludge Bomb"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.83% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Lycanroc-Dusk": {
    item: "Focus Sash",
    ability: "Tough Claws",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Accelerock", "Protect", "Close Combat", "Rock Slide"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.78% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Politoed": {
    item: "Sitrus Berry",
    ability: "Drizzle",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Weather Ball", "Protect", "Perish Song", "Ice Beam"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.58% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Primarina": {
    item: "Leftovers",
    ability: "Liquid Voice",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Hyper Voice", "Protect", "Moonblast", "Calm Mind"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.54% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Metagross": {
    item: "Life Orb",
    ability: "Clear Body",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Protect", "Psychic Fangs", "Iron Head", "Bullet Punch"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.52% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Gardevoir": {
    item: "Choice Scarf",
    ability: "Trace",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Hyper Voice", "Protect", "Psychic", "Psyshock"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.50% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Vivillon": {
    item: "Choice Scarf",
    ability: "Compound Eyes",
    nature: "Calm",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Sleep Powder", "Hurricane", "Rage Powder", "Tailwind"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.49% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Annihilape": {
    item: "Leftovers",
    ability: "Defiant",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Rage Fist", "Protect", "Drain Punch", "Bulk Up"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.45% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Kommo-o": {
    item: "Leftovers",
    ability: "Soundproof",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Clanging Scales", "Protect", "Clangorous Soul", "Aura Sphere"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.43% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Blaziken": {
    item: "Focus Sash",
    ability: "Speed Boost",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Close Combat", "Flare Blitz", "Protect", "Detect"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.42% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Tsareena": {
    item: "Choice Scarf",
    ability: "Queenly Majesty",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Triple Axel", "Trop Kick", "Protect", "Low Kick"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.42% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Hydreigon": {
    item: "Choice Scarf",
    ability: "Levitate",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Dark Pulse", "Draco Meteor", "Snarl", "Earth Power"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.39% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Ceruledge": {
    item: "Colbur Berry",
    ability: "Flash Fire",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Bitter Blade", "Protect", "Shadow Sneak", "Bulk Up"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.36% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Scrafty": {
    item: "Sitrus Berry",
    ability: "Intimidate",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Fake Out", "Knock Off", "Drain Punch", "Close Combat"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.36% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Corviknight": {
    item: "Leftovers",
    ability: "Mirror Armor",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Brave Bird", "Tailwind", "Iron Head", "Bulk Up"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.35% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Scizor": {
    item: "Life Orb",
    ability: "Technician",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Bullet Punch", "Protect", "Swords Dance", "Bug Bite"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.32% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Kangaskhan": {
    item: "Silk Scarf",
    ability: "Scrappy",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Fake Out", "Last Resort", "Double-Edge", "Ice Punch"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.30% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Camerupt": {
    item: "Choice Scarf",
    ability: "Solid Rock",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Earth Power", "Protect", "Heat Wave", "Ancient Power"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.29% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Hatterene": {
    item: "Life Orb",
    ability: "Magic Bounce",
    nature: "Calm",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Dazzling Gleam", "Trick Room", "Protect", "Psychic"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.29% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Clefable": {
    item: "Sitrus Berry",
    ability: "Unaware",
    nature: "Calm",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Moonblast", "Follow Me", "Protect", "Helping Hand"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.26% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Lucario": {
    item: "Choice Scarf",
    ability: "Inner Focus",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Close Combat", "Protect", "Final Gambit", "Bullet Punch"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.26% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Mimikyu": {
    item: "Life Orb",
    ability: "Disguise",
    nature: "Careful",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Play Rough", "Shadow Sneak", "Trick Room", "Shadow Claw"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.24% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Gallade": {
    item: "Focus Sash",
    ability: "Sharpness",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Sacred Sword", "Psycho Cut", "Protect", "Leaf Blade"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.22% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Volcarona": {
    item: "Leftovers",
    ability: "Flame Body",
    nature: "Calm",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Heat Wave", "Quiver Dance", "Protect", "Rage Powder"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.21% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Gyarados": {
    item: "Sitrus Berry",
    ability: "Intimidate",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Waterfall", "Protect", "Dragon Dance", "Crunch"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.20% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Azumarill": {
    item: "Sitrus Berry",
    ability: "Huge Power",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Play Rough", "Aqua Jet", "Protect", "Belly Drum"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.19% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Kleavor": {
    item: "Choice Scarf",
    ability: "Sharpness",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Stone Axe", "X-Scissor", "Close Combat", "Protect"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.18% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Armarouge": {
    item: "Sitrus Berry",
    ability: "Flash Fire",
    nature: "Calm",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Psychic", "Trick Room", "Heat Wave", "Protect"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.18% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Samurott-Hisui": {
    item: "Focus Sash",
    ability: "Sharpness",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Sacred Sword", "Aqua Cutter", "Ceaseless Edge", "Night Slash"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.17% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Araquanid": {
    item: "Mystic Water",
    ability: "Water Bubble",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Liquidation", "Wide Guard", "Protect", "Leech Life"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.17% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Drampa": {
    item: "Silk Scarf",
    ability: "Cloud Nine",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Hyper Voice", "Protect", "Earth Power", "Calm Mind"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.16% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Mamoswine": {
    item: "Focus Sash",
    ability: "Oblivious",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Ice Shard", "Icicle Crash", "Protect", "High Horsepower"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.16% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Meowscarada": {
    item: "Choice Scarf",
    ability: "Protean",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Flower Trick", "Triple Axel", "Knock Off", "Sucker Punch"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.16% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Zoroark-Hisui": {
    item: "Choice Scarf",
    ability: "Illusion",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Shadow Ball", "Hyper Voice", "Icy Wind", "Bitter Malice"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.16% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Meowstic": {
    item: "Light Clay",
    ability: "Prankster",
    nature: "Careful",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Fake Out", "Reflect", "Light Screen", "Charm"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.14% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Meganium": {
    item: "Zeraorite",
    ability: "Overgrow",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Solar Beam", "Weather Ball", "Dazzling Gleam", "Protect"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.14% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Houndstone": {
    item: "Life Orb",
    ability: "Sand Rush",
    nature: "Careful",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Last Respects", "Protect", "Will-O-Wisp", "Ally Switch"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.14% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Snorlax": {
    item: "Leftovers",
    ability: "Thick Fat",
    nature: "Careful",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Protect", "Fissure", "Yawn", "Stockpile"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.14% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Vanilluxe": {
    item: "Choice Scarf",
    ability: "Snow Warning",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Blizzard", "Freeze-Dry", "Icy Wind", "Aurora Veil"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.13% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Weavile": {
    item: "Focus Sash",
    ability: "Pickpocket",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Fake Out", "Knock Off", "Triple Axel", "Protect"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.13% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Malamar": {
    item: "Mental Herb",
    ability: "Contrary",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Superpower", "Protect", "Knock Off", "Psycho Cut"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.13% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Tinkaton": {
    item: "Occa Berry",
    ability: "Mold Breaker",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Gigaton Hammer", "Fake Out", "Play Rough", "Encore"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.13% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Golurk": {
    item: "White Herb",
    ability: "Iron Fist",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Protect", "Headlong Rush", "Poltergeist", "Ice Punch"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.12% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Rotom-Heat": {
    item: "Choice Scarf",
    ability: "Levitate",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Overheat", "Volt Switch", "Will-O-Wisp", "Thunderbolt"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.12% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Greninja": {
    item: "Life Orb",
    ability: "Protean",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Ice Beam", "Dark Pulse", "Protect", "Grass Knot"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.12% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Palafin": {
    item: "Mystic Water",
    ability: "Zero to Hero",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Jet Punch", "Wave Crash", "Protect", "Close Combat"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.11% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Vileplume": {
    item: "Wide Lens",
    ability: "Chlorophyll",
    nature: "Calm",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Sleep Powder", "Sludge Bomb", "After You", "Protect"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.11% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Absol": {
    item: "Scope Lens",
    ability: "Super Luck",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Protect", "Close Combat", "Sucker Punch", "Night Slash"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.11% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Sceptile": {
    item: "White Herb",
    ability: "Overgrow",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Dragon Pulse", "Earth Power", "Detect", "Energy Ball"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.11% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Chandelure": {
    item: "Focus Sash",
    ability: "Flash Fire",
    nature: "Calm",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Shadow Ball", "Heat Wave", "Protect", "Trick Room"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.10% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Dragapult": {
    item: "Life Orb",
    ability: "Clear Body",
    nature: "Jolly",
    sp: { hp: 4, atk: 30, spe: 32 },
    moves: ["Protect", "Draco Meteor", "Dragon Darts", "Will-O-Wisp"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.10% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Altaria": {
    item: "Sitrus Berry",
    ability: "Cloud Nine",
    nature: "Calm",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Tailwind", "Hyper Voice", "Protect", "Will-O-Wisp"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.10% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Espathra": {
    item: "Sitrus Berry",
    ability: "Speed Boost",
    nature: "Calm",
    sp: { hp: 20, def: 20, spd: 20 },
    moves: ["Protect", "Calm Mind", "Lumina Crash", "Baton Pass"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.09% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
  "Salazzle": {
    item: "Focus Sash",
    ability: "Corrosion",
    nature: "Timid",
    sp: { hp: 4, spa: 30, spe: 32 },
    moves: ["Fake Out", "Sludge Bomb", "Heat Wave", "Protect"],
    source: "Pikalytics live usage feed (Reg M-B S3, 0.08% usage) — item/ability/moves decoded from @pkmn/dex ids; SP is a role-based default (not from this feed)",
    spConfirmed: false,
  },
};

export function getMetaSet(species: string): MetaSet | null {
  return META_SETS[species] ?? null;
}